/*
 * File: BytesToFdm.c
 *
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is an S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_defines_Changes_BEGIN
  *        #define NAME 'replacement text' 
  *        %%% SFUNWIZ_defines_Changes_END
  *
  *   DO NOT change NAME--Change the 'replacement text' only.
  *
  *   For better compatibility with the Simulink Coder, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Simulink Coder's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *  -------------------------------------------------------------------------
  * | See matlabroot/simulink/src/sfuntmpl_doc.c for a more detailed template |
  *  ------------------------------------------------------------------------- 
* Created: Tue Nov  1 18:05:00 2016
*/
#define S_FUNCTION_LEVEL 2
#define S_FUNCTION_NAME BytesToFdm
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
/* %%%-SFUNWIZ_defines_Changes_BEGIN --- EDIT HERE TO _END */
#define NUM_INPUTS          1
/* Input Port  0 */
#define IN_PORT_0_NAME      Input
#define INPUT_0_WIDTH       408
#define INPUT_DIMS_0_COL    1
#define INPUT_0_DTYPE       uint8_T
#define INPUT_0_COMPLEX     COMPLEX_NO
#define IN_0_FRAME_BASED    FRAME_NO
#define IN_0_BUS_BASED      0
#define IN_0_BUS_NAME       
#define IN_0_DIMS           2-D
#define INPUT_0_FEEDTHROUGH 1
#define IN_0_ISSIGNED        0
#define IN_0_WORDLENGTH      8
#define IN_0_FIXPOINTSCALING 1
#define IN_0_FRACTIONLENGTH  9
#define IN_0_BIAS            0
#define IN_0_SLOPE           0.125

#define NUM_OUTPUTS          58
/* Output Port  0 */
#define OUT_PORT_0_NAME      Version
#define OUTPUT_0_WIDTH       1
#define OUTPUT_DIMS_0_COL    1
#define OUTPUT_0_DTYPE       uint32_T
#define OUTPUT_0_COMPLEX     COMPLEX_NO
#define OUT_0_FRAME_BASED    FRAME_NO
#define OUT_0_BUS_BASED      0
#define OUT_0_BUS_NAME       
#define OUT_0_DIMS           1-D
#define OUT_0_ISSIGNED        1
#define OUT_0_WORDLENGTH      8
#define OUT_0_FIXPOINTSCALING 1
#define OUT_0_FRACTIONLENGTH  3
#define OUT_0_BIAS            0
#define OUT_0_SLOPE           0.125
/* Output Port  1 */
#define OUT_PORT_1_NAME      padding
#define OUTPUT_1_WIDTH       1
#define OUTPUT_DIMS_1_COL    1
#define OUTPUT_1_DTYPE       uint32_T
#define OUTPUT_1_COMPLEX     COMPLEX_NO
#define OUT_1_FRAME_BASED    FRAME_NO
#define OUT_1_BUS_BASED      0
#define OUT_1_BUS_NAME       
#define OUT_1_DIMS           1-D
#define OUT_1_ISSIGNED        1
#define OUT_1_WORDLENGTH      8
#define OUT_1_FIXPOINTSCALING 1
#define OUT_1_FRACTIONLENGTH  3
#define OUT_1_BIAS            0
#define OUT_1_SLOPE           0.125
/* Output Port  2 */
#define OUT_PORT_2_NAME      longitude
#define OUTPUT_2_WIDTH       1
#define OUTPUT_DIMS_2_COL    1
#define OUTPUT_2_DTYPE       real_T
#define OUTPUT_2_COMPLEX     COMPLEX_NO
#define OUT_2_FRAME_BASED    FRAME_NO
#define OUT_2_BUS_BASED      0
#define OUT_2_BUS_NAME       
#define OUT_2_DIMS           1-D
#define OUT_2_ISSIGNED        1
#define OUT_2_WORDLENGTH      8
#define OUT_2_FIXPOINTSCALING 1
#define OUT_2_FRACTIONLENGTH  3
#define OUT_2_BIAS            0
#define OUT_2_SLOPE           0.125
/* Output Port  3 */
#define OUT_PORT_3_NAME      latitude
#define OUTPUT_3_WIDTH       1
#define OUTPUT_DIMS_3_COL    1
#define OUTPUT_3_DTYPE       real_T
#define OUTPUT_3_COMPLEX     COMPLEX_NO
#define OUT_3_FRAME_BASED    FRAME_NO
#define OUT_3_BUS_BASED      0
#define OUT_3_BUS_NAME       
#define OUT_3_DIMS           1-D
#define OUT_3_ISSIGNED        1
#define OUT_3_WORDLENGTH      8
#define OUT_3_FIXPOINTSCALING 1
#define OUT_3_FRACTIONLENGTH  3
#define OUT_3_BIAS            0
#define OUT_3_SLOPE           0.125
/* Output Port  4 */
#define OUT_PORT_4_NAME      altitude
#define OUTPUT_4_WIDTH       1
#define OUTPUT_DIMS_4_COL    1
#define OUTPUT_4_DTYPE       real_T
#define OUTPUT_4_COMPLEX     COMPLEX_NO
#define OUT_4_FRAME_BASED    FRAME_NO
#define OUT_4_BUS_BASED      0
#define OUT_4_BUS_NAME       
#define OUT_4_DIMS           1-D
#define OUT_4_ISSIGNED        1
#define OUT_4_WORDLENGTH      8
#define OUT_4_FIXPOINTSCALING 1
#define OUT_4_FRACTIONLENGTH  3
#define OUT_4_BIAS            0
#define OUT_4_SLOPE           0.125
/* Output Port  5 */
#define OUT_PORT_5_NAME      agl
#define OUTPUT_5_WIDTH       1
#define OUTPUT_DIMS_5_COL    1
#define OUTPUT_5_DTYPE       real32_T
#define OUTPUT_5_COMPLEX     COMPLEX_NO
#define OUT_5_FRAME_BASED    FRAME_NO
#define OUT_5_BUS_BASED      0
#define OUT_5_BUS_NAME       
#define OUT_5_DIMS           1-D
#define OUT_5_ISSIGNED        1
#define OUT_5_WORDLENGTH      8
#define OUT_5_FIXPOINTSCALING 1
#define OUT_5_FRACTIONLENGTH  3
#define OUT_5_BIAS            0
#define OUT_5_SLOPE           0.125
/* Output Port  6 */
#define OUT_PORT_6_NAME      phi
#define OUTPUT_6_WIDTH       1
#define OUTPUT_DIMS_6_COL    1
#define OUTPUT_6_DTYPE       real32_T
#define OUTPUT_6_COMPLEX     COMPLEX_NO
#define OUT_6_FRAME_BASED    FRAME_NO
#define OUT_6_BUS_BASED      0
#define OUT_6_BUS_NAME       
#define OUT_6_DIMS           1-D
#define OUT_6_ISSIGNED        1
#define OUT_6_WORDLENGTH      8
#define OUT_6_FIXPOINTSCALING 1
#define OUT_6_FRACTIONLENGTH  3
#define OUT_6_BIAS            0
#define OUT_6_SLOPE           0.125
/* Output Port  7 */
#define OUT_PORT_7_NAME      theta
#define OUTPUT_7_WIDTH       1
#define OUTPUT_DIMS_7_COL    1
#define OUTPUT_7_DTYPE       real32_T
#define OUTPUT_7_COMPLEX     COMPLEX_NO
#define OUT_7_FRAME_BASED    FRAME_NO
#define OUT_7_BUS_BASED      0
#define OUT_7_BUS_NAME       
#define OUT_7_DIMS           1-D
#define OUT_7_ISSIGNED        1
#define OUT_7_WORDLENGTH      8
#define OUT_7_FIXPOINTSCALING 1
#define OUT_7_FRACTIONLENGTH  3
#define OUT_7_BIAS            0
#define OUT_7_SLOPE           0.125
/* Output Port  8 */
#define OUT_PORT_8_NAME      psi
#define OUTPUT_8_WIDTH       1
#define OUTPUT_DIMS_8_COL    1
#define OUTPUT_8_DTYPE       real32_T
#define OUTPUT_8_COMPLEX     COMPLEX_NO
#define OUT_8_FRAME_BASED    FRAME_NO
#define OUT_8_BUS_BASED      0
#define OUT_8_BUS_NAME       
#define OUT_8_DIMS           1-D
#define OUT_8_ISSIGNED        1
#define OUT_8_WORDLENGTH      8
#define OUT_8_FIXPOINTSCALING 1
#define OUT_8_FRACTIONLENGTH  3
#define OUT_8_BIAS            0
#define OUT_8_SLOPE           0.125
/* Output Port  9 */
#define OUT_PORT_9_NAME      alpha
#define OUTPUT_9_WIDTH       1
#define OUTPUT_DIMS_9_COL    1
#define OUTPUT_9_DTYPE       real32_T
#define OUTPUT_9_COMPLEX     COMPLEX_NO
#define OUT_9_FRAME_BASED    FRAME_NO
#define OUT_9_BUS_BASED      0
#define OUT_9_BUS_NAME       
#define OUT_9_DIMS           1-D
#define OUT_9_ISSIGNED        1
#define OUT_9_WORDLENGTH      8
#define OUT_9_FIXPOINTSCALING 1
#define OUT_9_FRACTIONLENGTH  3
#define OUT_9_BIAS            0
#define OUT_9_SLOPE           0.125
/* Output Port  10 */
#define OUT_PORT_10_NAME      beta
#define OUTPUT_10_WIDTH       1
#define OUTPUT_DIMS_10_COL    1
#define OUTPUT_10_DTYPE       real32_T
#define OUTPUT_10_COMPLEX     COMPLEX_NO
#define OUT_10_FRAME_BASED    FRAME_NO
#define OUT_10_BUS_BASED      0
#define OUT_10_BUS_NAME       
#define OUT_10_DIMS           1-D
#define OUT_10_ISSIGNED        1
#define OUT_10_WORDLENGTH      8
#define OUT_10_FIXPOINTSCALING 1
#define OUT_10_FRACTIONLENGTH  3
#define OUT_10_BIAS            0
#define OUT_10_SLOPE           0.125
/* Output Port  11 */
#define OUT_PORT_11_NAME      phidot
#define OUTPUT_11_WIDTH       1
#define OUTPUT_DIMS_11_COL    1
#define OUTPUT_11_DTYPE       real32_T
#define OUTPUT_11_COMPLEX     COMPLEX_NO
#define OUT_11_FRAME_BASED    FRAME_NO
#define OUT_11_BUS_BASED      0
#define OUT_11_BUS_NAME       
#define OUT_11_DIMS           1-D
#define OUT_11_ISSIGNED        1
#define OUT_11_WORDLENGTH      8
#define OUT_11_FIXPOINTSCALING 1
#define OUT_11_FRACTIONLENGTH  3
#define OUT_11_BIAS            0
#define OUT_11_SLOPE           0.125
/* Output Port  12 */
#define OUT_PORT_12_NAME      thetadot
#define OUTPUT_12_WIDTH       1
#define OUTPUT_DIMS_12_COL    1
#define OUTPUT_12_DTYPE       real32_T
#define OUTPUT_12_COMPLEX     COMPLEX_NO
#define OUT_12_FRAME_BASED    FRAME_NO
#define OUT_12_BUS_BASED      0
#define OUT_12_BUS_NAME       
#define OUT_12_DIMS           1-D
#define OUT_12_ISSIGNED        1
#define OUT_12_WORDLENGTH      8
#define OUT_12_FIXPOINTSCALING 1
#define OUT_12_FRACTIONLENGTH  3
#define OUT_12_BIAS            0
#define OUT_12_SLOPE           0.125
/* Output Port  13 */
#define OUT_PORT_13_NAME      psidot
#define OUTPUT_13_WIDTH       1
#define OUTPUT_DIMS_13_COL    1
#define OUTPUT_13_DTYPE       real32_T
#define OUTPUT_13_COMPLEX     COMPLEX_NO
#define OUT_13_FRAME_BASED    FRAME_NO
#define OUT_13_BUS_BASED      0
#define OUT_13_BUS_NAME       
#define OUT_13_DIMS           1-D
#define OUT_13_ISSIGNED        1
#define OUT_13_WORDLENGTH      8
#define OUT_13_FIXPOINTSCALING 1
#define OUT_13_FRACTIONLENGTH  3
#define OUT_13_BIAS            0
#define OUT_13_SLOPE           0.125
/* Output Port  14 */
#define OUT_PORT_14_NAME      vcas
#define OUTPUT_14_WIDTH       1
#define OUTPUT_DIMS_14_COL    1
#define OUTPUT_14_DTYPE       real32_T
#define OUTPUT_14_COMPLEX     COMPLEX_NO
#define OUT_14_FRAME_BASED    FRAME_NO
#define OUT_14_BUS_BASED      0
#define OUT_14_BUS_NAME       
#define OUT_14_DIMS           1-D
#define OUT_14_ISSIGNED        1
#define OUT_14_WORDLENGTH      8
#define OUT_14_FIXPOINTSCALING 1
#define OUT_14_FRACTIONLENGTH  3
#define OUT_14_BIAS            0
#define OUT_14_SLOPE           0.125
/* Output Port  15 */
#define OUT_PORT_15_NAME      climb_rate
#define OUTPUT_15_WIDTH       1
#define OUTPUT_DIMS_15_COL    1
#define OUTPUT_15_DTYPE       real32_T
#define OUTPUT_15_COMPLEX     COMPLEX_NO
#define OUT_15_FRAME_BASED    FRAME_NO
#define OUT_15_BUS_BASED      0
#define OUT_15_BUS_NAME       
#define OUT_15_DIMS           1-D
#define OUT_15_ISSIGNED        1
#define OUT_15_WORDLENGTH      8
#define OUT_15_FIXPOINTSCALING 1
#define OUT_15_FRACTIONLENGTH  3
#define OUT_15_BIAS            0
#define OUT_15_SLOPE           0.125
/* Output Port  16 */
#define OUT_PORT_16_NAME      v_north
#define OUTPUT_16_WIDTH       1
#define OUTPUT_DIMS_16_COL    1
#define OUTPUT_16_DTYPE       real32_T
#define OUTPUT_16_COMPLEX     COMPLEX_NO
#define OUT_16_FRAME_BASED    FRAME_NO
#define OUT_16_BUS_BASED      0
#define OUT_16_BUS_NAME       
#define OUT_16_DIMS           1-D
#define OUT_16_ISSIGNED        1
#define OUT_16_WORDLENGTH      8
#define OUT_16_FIXPOINTSCALING 1
#define OUT_16_FRACTIONLENGTH  3
#define OUT_16_BIAS            0
#define OUT_16_SLOPE           0.125
/* Output Port  17 */
#define OUT_PORT_17_NAME      v_east
#define OUTPUT_17_WIDTH       1
#define OUTPUT_DIMS_17_COL    1
#define OUTPUT_17_DTYPE       real32_T
#define OUTPUT_17_COMPLEX     COMPLEX_NO
#define OUT_17_FRAME_BASED    FRAME_NO
#define OUT_17_BUS_BASED      0
#define OUT_17_BUS_NAME       
#define OUT_17_DIMS           1-D
#define OUT_17_ISSIGNED        1
#define OUT_17_WORDLENGTH      8
#define OUT_17_FIXPOINTSCALING 1
#define OUT_17_FRACTIONLENGTH  3
#define OUT_17_BIAS            0
#define OUT_17_SLOPE           0.125
/* Output Port  18 */
#define OUT_PORT_18_NAME      v_down
#define OUTPUT_18_WIDTH       1
#define OUTPUT_DIMS_18_COL    1
#define OUTPUT_18_DTYPE       real32_T
#define OUTPUT_18_COMPLEX     COMPLEX_NO
#define OUT_18_FRAME_BASED    FRAME_NO
#define OUT_18_BUS_BASED      0
#define OUT_18_BUS_NAME       
#define OUT_18_DIMS           1-D
#define OUT_18_ISSIGNED        1
#define OUT_18_WORDLENGTH      8
#define OUT_18_FIXPOINTSCALING 1
#define OUT_18_FRACTIONLENGTH  3
#define OUT_18_BIAS            0
#define OUT_18_SLOPE           0.125
/* Output Port  19 */
#define OUT_PORT_19_NAME      v_body_u
#define OUTPUT_19_WIDTH       1
#define OUTPUT_DIMS_19_COL    1
#define OUTPUT_19_DTYPE       real32_T
#define OUTPUT_19_COMPLEX     COMPLEX_NO
#define OUT_19_FRAME_BASED    FRAME_NO
#define OUT_19_BUS_BASED      0
#define OUT_19_BUS_NAME       
#define OUT_19_DIMS           1-D
#define OUT_19_ISSIGNED        1
#define OUT_19_WORDLENGTH      8
#define OUT_19_FIXPOINTSCALING 1
#define OUT_19_FRACTIONLENGTH  3
#define OUT_19_BIAS            0
#define OUT_19_SLOPE           0.125
/* Output Port  20 */
#define OUT_PORT_20_NAME      v_body_v
#define OUTPUT_20_WIDTH       1
#define OUTPUT_DIMS_20_COL    1
#define OUTPUT_20_DTYPE       real32_T
#define OUTPUT_20_COMPLEX     COMPLEX_NO
#define OUT_20_FRAME_BASED    FRAME_NO
#define OUT_20_BUS_BASED      0
#define OUT_20_BUS_NAME       
#define OUT_20_DIMS           1-D
#define OUT_20_ISSIGNED        1
#define OUT_20_WORDLENGTH      8
#define OUT_20_FIXPOINTSCALING 1
#define OUT_20_FRACTIONLENGTH  3
#define OUT_20_BIAS            0
#define OUT_20_SLOPE           0.125
/* Output Port  21 */
#define OUT_PORT_21_NAME      v_body_w
#define OUTPUT_21_WIDTH       1
#define OUTPUT_DIMS_21_COL    1
#define OUTPUT_21_DTYPE       real32_T
#define OUTPUT_21_COMPLEX     COMPLEX_NO
#define OUT_21_FRAME_BASED    FRAME_NO
#define OUT_21_BUS_BASED      0
#define OUT_21_BUS_NAME       
#define OUT_21_DIMS           1-D
#define OUT_21_ISSIGNED        1
#define OUT_21_WORDLENGTH      8
#define OUT_21_FIXPOINTSCALING 1
#define OUT_21_FRACTIONLENGTH  3
#define OUT_21_BIAS            0
#define OUT_21_SLOPE           0.125
/* Output Port  22 */
#define OUT_PORT_22_NAME      A_X_pilot
#define OUTPUT_22_WIDTH       1
#define OUTPUT_DIMS_22_COL    1
#define OUTPUT_22_DTYPE       real32_T
#define OUTPUT_22_COMPLEX     COMPLEX_NO
#define OUT_22_FRAME_BASED    FRAME_NO
#define OUT_22_BUS_BASED      0
#define OUT_22_BUS_NAME       
#define OUT_22_DIMS           1-D
#define OUT_22_ISSIGNED        1
#define OUT_22_WORDLENGTH      8
#define OUT_22_FIXPOINTSCALING 1
#define OUT_22_FRACTIONLENGTH  3
#define OUT_22_BIAS            0
#define OUT_22_SLOPE           0.125
/* Output Port  23 */
#define OUT_PORT_23_NAME      A_Y_pilot
#define OUTPUT_23_WIDTH       1
#define OUTPUT_DIMS_23_COL    1
#define OUTPUT_23_DTYPE       real32_T
#define OUTPUT_23_COMPLEX     COMPLEX_NO
#define OUT_23_FRAME_BASED    FRAME_NO
#define OUT_23_BUS_BASED      0
#define OUT_23_BUS_NAME       
#define OUT_23_DIMS           1-D
#define OUT_23_ISSIGNED        1
#define OUT_23_WORDLENGTH      8
#define OUT_23_FIXPOINTSCALING 1
#define OUT_23_FRACTIONLENGTH  3
#define OUT_23_BIAS            0
#define OUT_23_SLOPE           0.125
/* Output Port  24 */
#define OUT_PORT_24_NAME      A_Z_pilot
#define OUTPUT_24_WIDTH       1
#define OUTPUT_DIMS_24_COL    1
#define OUTPUT_24_DTYPE       real32_T
#define OUTPUT_24_COMPLEX     COMPLEX_NO
#define OUT_24_FRAME_BASED    FRAME_NO
#define OUT_24_BUS_BASED      0
#define OUT_24_BUS_NAME       
#define OUT_24_DIMS           1-D
#define OUT_24_ISSIGNED        1
#define OUT_24_WORDLENGTH      8
#define OUT_24_FIXPOINTSCALING 1
#define OUT_24_FRACTIONLENGTH  3
#define OUT_24_BIAS            0
#define OUT_24_SLOPE           0.125
/* Output Port  25 */
#define OUT_PORT_25_NAME      stall_warning
#define OUTPUT_25_WIDTH       1
#define OUTPUT_DIMS_25_COL    1
#define OUTPUT_25_DTYPE       real32_T
#define OUTPUT_25_COMPLEX     COMPLEX_NO
#define OUT_25_FRAME_BASED    FRAME_NO
#define OUT_25_BUS_BASED      0
#define OUT_25_BUS_NAME       
#define OUT_25_DIMS           1-D
#define OUT_25_ISSIGNED        1
#define OUT_25_WORDLENGTH      8
#define OUT_25_FIXPOINTSCALING 1
#define OUT_25_FRACTIONLENGTH  3
#define OUT_25_BIAS            0
#define OUT_25_SLOPE           0.125
/* Output Port  26 */
#define OUT_PORT_26_NAME      slip_deg
#define OUTPUT_26_WIDTH       1
#define OUTPUT_DIMS_26_COL    1
#define OUTPUT_26_DTYPE       real32_T
#define OUTPUT_26_COMPLEX     COMPLEX_NO
#define OUT_26_FRAME_BASED    FRAME_NO
#define OUT_26_BUS_BASED      0
#define OUT_26_BUS_NAME       
#define OUT_26_DIMS           1-D
#define OUT_26_ISSIGNED        1
#define OUT_26_WORDLENGTH      8
#define OUT_26_FIXPOINTSCALING 1
#define OUT_26_FRACTIONLENGTH  3
#define OUT_26_BIAS            0
#define OUT_26_SLOPE           0.125
/* Output Port  27 */
#define OUT_PORT_27_NAME      num_engines
#define OUTPUT_27_WIDTH       1
#define OUTPUT_DIMS_27_COL    1
#define OUTPUT_27_DTYPE       uint32_T
#define OUTPUT_27_COMPLEX     COMPLEX_NO
#define OUT_27_FRAME_BASED    FRAME_NO
#define OUT_27_BUS_BASED      0
#define OUT_27_BUS_NAME       
#define OUT_27_DIMS           1-D
#define OUT_27_ISSIGNED        1
#define OUT_27_WORDLENGTH      8
#define OUT_27_FIXPOINTSCALING 1
#define OUT_27_FRACTIONLENGTH  3
#define OUT_27_BIAS            0
#define OUT_27_SLOPE           0.125
/* Output Port  28 */
#define OUT_PORT_28_NAME      eng_state
#define OUTPUT_28_WIDTH       4
#define OUTPUT_DIMS_28_COL    1
#define OUTPUT_28_DTYPE       uint32_T
#define OUTPUT_28_COMPLEX     COMPLEX_NO
#define OUT_28_FRAME_BASED    FRAME_NO
#define OUT_28_BUS_BASED      0
#define OUT_28_BUS_NAME       
#define OUT_28_DIMS           1-D
#define OUT_28_ISSIGNED        1
#define OUT_28_WORDLENGTH      8
#define OUT_28_FIXPOINTSCALING 1
#define OUT_28_FRACTIONLENGTH  3
#define OUT_28_BIAS            0
#define OUT_28_SLOPE           0.125
/* Output Port  29 */
#define OUT_PORT_29_NAME      rpm
#define OUTPUT_29_WIDTH       4
#define OUTPUT_DIMS_29_COL    1
#define OUTPUT_29_DTYPE       real32_T
#define OUTPUT_29_COMPLEX     COMPLEX_NO
#define OUT_29_FRAME_BASED    FRAME_NO
#define OUT_29_BUS_BASED      0
#define OUT_29_BUS_NAME       
#define OUT_29_DIMS           1-D
#define OUT_29_ISSIGNED        1
#define OUT_29_WORDLENGTH      8
#define OUT_29_FIXPOINTSCALING 1
#define OUT_29_FRACTIONLENGTH  3
#define OUT_29_BIAS            0
#define OUT_29_SLOPE           0.125
/* Output Port  30 */
#define OUT_PORT_30_NAME      fuel_flow
#define OUTPUT_30_WIDTH       4
#define OUTPUT_DIMS_30_COL    1
#define OUTPUT_30_DTYPE       real32_T
#define OUTPUT_30_COMPLEX     COMPLEX_NO
#define OUT_30_FRAME_BASED    FRAME_NO
#define OUT_30_BUS_BASED      0
#define OUT_30_BUS_NAME       
#define OUT_30_DIMS           1-D
#define OUT_30_ISSIGNED        1
#define OUT_30_WORDLENGTH      8
#define OUT_30_FIXPOINTSCALING 1
#define OUT_30_FRACTIONLENGTH  3
#define OUT_30_BIAS            0
#define OUT_30_SLOPE           0.125
/* Output Port  31 */
#define OUT_PORT_31_NAME      fuel_px
#define OUTPUT_31_WIDTH       4
#define OUTPUT_DIMS_31_COL    1
#define OUTPUT_31_DTYPE       real32_T
#define OUTPUT_31_COMPLEX     COMPLEX_NO
#define OUT_31_FRAME_BASED    FRAME_NO
#define OUT_31_BUS_BASED      0
#define OUT_31_BUS_NAME       
#define OUT_31_DIMS           1-D
#define OUT_31_ISSIGNED        1
#define OUT_31_WORDLENGTH      8
#define OUT_31_FIXPOINTSCALING 1
#define OUT_31_FRACTIONLENGTH  3
#define OUT_31_BIAS            0
#define OUT_31_SLOPE           0.125
/* Output Port  32 */
#define OUT_PORT_32_NAME      egt
#define OUTPUT_32_WIDTH       4
#define OUTPUT_DIMS_32_COL    1
#define OUTPUT_32_DTYPE       real32_T
#define OUTPUT_32_COMPLEX     COMPLEX_NO
#define OUT_32_FRAME_BASED    FRAME_NO
#define OUT_32_BUS_BASED      0
#define OUT_32_BUS_NAME       
#define OUT_32_DIMS           1-D
#define OUT_32_ISSIGNED        1
#define OUT_32_WORDLENGTH      8
#define OUT_32_FIXPOINTSCALING 1
#define OUT_32_FRACTIONLENGTH  3
#define OUT_32_BIAS            0
#define OUT_32_SLOPE           0.125
/* Output Port  33 */
#define OUT_PORT_33_NAME      cht
#define OUTPUT_33_WIDTH       4
#define OUTPUT_DIMS_33_COL    1
#define OUTPUT_33_DTYPE       real32_T
#define OUTPUT_33_COMPLEX     COMPLEX_NO
#define OUT_33_FRAME_BASED    FRAME_NO
#define OUT_33_BUS_BASED      0
#define OUT_33_BUS_NAME       
#define OUT_33_DIMS           1-D
#define OUT_33_ISSIGNED        1
#define OUT_33_WORDLENGTH      8
#define OUT_33_FIXPOINTSCALING 1
#define OUT_33_FRACTIONLENGTH  3
#define OUT_33_BIAS            0
#define OUT_33_SLOPE           0.125
/* Output Port  34 */
#define OUT_PORT_34_NAME      mp_osi
#define OUTPUT_34_WIDTH       4
#define OUTPUT_DIMS_34_COL    1
#define OUTPUT_34_DTYPE       real32_T
#define OUTPUT_34_COMPLEX     COMPLEX_NO
#define OUT_34_FRAME_BASED    FRAME_NO
#define OUT_34_BUS_BASED      0
#define OUT_34_BUS_NAME       
#define OUT_34_DIMS           1-D
#define OUT_34_ISSIGNED        1
#define OUT_34_WORDLENGTH      8
#define OUT_34_FIXPOINTSCALING 1
#define OUT_34_FRACTIONLENGTH  3
#define OUT_34_BIAS            0
#define OUT_34_SLOPE           0.125
/* Output Port  35 */
#define OUT_PORT_35_NAME      tit
#define OUTPUT_35_WIDTH       4
#define OUTPUT_DIMS_35_COL    1
#define OUTPUT_35_DTYPE       real32_T
#define OUTPUT_35_COMPLEX     COMPLEX_NO
#define OUT_35_FRAME_BASED    FRAME_NO
#define OUT_35_BUS_BASED      0
#define OUT_35_BUS_NAME       
#define OUT_35_DIMS           1-D
#define OUT_35_ISSIGNED        1
#define OUT_35_WORDLENGTH      8
#define OUT_35_FIXPOINTSCALING 1
#define OUT_35_FRACTIONLENGTH  3
#define OUT_35_BIAS            0
#define OUT_35_SLOPE           0.125
/* Output Port  36 */
#define OUT_PORT_36_NAME      oil_temp
#define OUTPUT_36_WIDTH       4
#define OUTPUT_DIMS_36_COL    1
#define OUTPUT_36_DTYPE       real32_T
#define OUTPUT_36_COMPLEX     COMPLEX_NO
#define OUT_36_FRAME_BASED    FRAME_NO
#define OUT_36_BUS_BASED      0
#define OUT_36_BUS_NAME       
#define OUT_36_DIMS           1-D
#define OUT_36_ISSIGNED        1
#define OUT_36_WORDLENGTH      8
#define OUT_36_FIXPOINTSCALING 1
#define OUT_36_FRACTIONLENGTH  3
#define OUT_36_BIAS            0
#define OUT_36_SLOPE           0.125
/* Output Port  37 */
#define OUT_PORT_37_NAME      oil_px
#define OUTPUT_37_WIDTH       4
#define OUTPUT_DIMS_37_COL    1
#define OUTPUT_37_DTYPE       real32_T
#define OUTPUT_37_COMPLEX     COMPLEX_NO
#define OUT_37_FRAME_BASED    FRAME_NO
#define OUT_37_BUS_BASED      0
#define OUT_37_BUS_NAME       
#define OUT_37_DIMS           1-D
#define OUT_37_ISSIGNED        1
#define OUT_37_WORDLENGTH      8
#define OUT_37_FIXPOINTSCALING 1
#define OUT_37_FRACTIONLENGTH  3
#define OUT_37_BIAS            0
#define OUT_37_SLOPE           0.125
/* Output Port  38 */
#define OUT_PORT_38_NAME      num_tanks
#define OUTPUT_38_WIDTH       1
#define OUTPUT_DIMS_38_COL    1
#define OUTPUT_38_DTYPE       uint32_T
#define OUTPUT_38_COMPLEX     COMPLEX_NO
#define OUT_38_FRAME_BASED    FRAME_NO
#define OUT_38_BUS_BASED      0
#define OUT_38_BUS_NAME       
#define OUT_38_DIMS           1-D
#define OUT_38_ISSIGNED        1
#define OUT_38_WORDLENGTH      8
#define OUT_38_FIXPOINTSCALING 1
#define OUT_38_FRACTIONLENGTH  3
#define OUT_38_BIAS            0
#define OUT_38_SLOPE           0.125
/* Output Port  39 */
#define OUT_PORT_39_NAME      fuel_quantity
#define OUTPUT_39_WIDTH       4
#define OUTPUT_DIMS_39_COL    1
#define OUTPUT_39_DTYPE       real32_T
#define OUTPUT_39_COMPLEX     COMPLEX_NO
#define OUT_39_FRAME_BASED    FRAME_NO
#define OUT_39_BUS_BASED      0
#define OUT_39_BUS_NAME       
#define OUT_39_DIMS           1-D
#define OUT_39_ISSIGNED        1
#define OUT_39_WORDLENGTH      8
#define OUT_39_FIXPOINTSCALING 1
#define OUT_39_FRACTIONLENGTH  3
#define OUT_39_BIAS            0
#define OUT_39_SLOPE           0.125
/* Output Port  40 */
#define OUT_PORT_40_NAME      num_wheels
#define OUTPUT_40_WIDTH       1
#define OUTPUT_DIMS_40_COL    1
#define OUTPUT_40_DTYPE       uint32_T
#define OUTPUT_40_COMPLEX     COMPLEX_NO
#define OUT_40_FRAME_BASED    FRAME_NO
#define OUT_40_BUS_BASED      0
#define OUT_40_BUS_NAME       
#define OUT_40_DIMS           1-D
#define OUT_40_ISSIGNED        1
#define OUT_40_WORDLENGTH      8
#define OUT_40_FIXPOINTSCALING 1
#define OUT_40_FRACTIONLENGTH  3
#define OUT_40_BIAS            0
#define OUT_40_SLOPE           0.125
/* Output Port  41 */
#define OUT_PORT_41_NAME      wow
#define OUTPUT_41_WIDTH       3
#define OUTPUT_DIMS_41_COL    1
#define OUTPUT_41_DTYPE       uint32_T
#define OUTPUT_41_COMPLEX     COMPLEX_NO
#define OUT_41_FRAME_BASED    FRAME_NO
#define OUT_41_BUS_BASED      0
#define OUT_41_BUS_NAME       
#define OUT_41_DIMS           1-D
#define OUT_41_ISSIGNED        1
#define OUT_41_WORDLENGTH      8
#define OUT_41_FIXPOINTSCALING 1
#define OUT_41_FRACTIONLENGTH  3
#define OUT_41_BIAS            0
#define OUT_41_SLOPE           0.125
/* Output Port  42 */
#define OUT_PORT_42_NAME      gear_pos
#define OUTPUT_42_WIDTH       3
#define OUTPUT_DIMS_42_COL    1
#define OUTPUT_42_DTYPE       real32_T
#define OUTPUT_42_COMPLEX     COMPLEX_NO
#define OUT_42_FRAME_BASED    FRAME_NO
#define OUT_42_BUS_BASED      0
#define OUT_42_BUS_NAME       
#define OUT_42_DIMS           1-D
#define OUT_42_ISSIGNED        1
#define OUT_42_WORDLENGTH      8
#define OUT_42_FIXPOINTSCALING 1
#define OUT_42_FRACTIONLENGTH  3
#define OUT_42_BIAS            0
#define OUT_42_SLOPE           0.125
/* Output Port  43 */
#define OUT_PORT_43_NAME      gear_steer
#define OUTPUT_43_WIDTH       3
#define OUTPUT_DIMS_43_COL    1
#define OUTPUT_43_DTYPE       real32_T
#define OUTPUT_43_COMPLEX     COMPLEX_NO
#define OUT_43_FRAME_BASED    FRAME_NO
#define OUT_43_BUS_BASED      0
#define OUT_43_BUS_NAME       
#define OUT_43_DIMS           1-D
#define OUT_43_ISSIGNED        1
#define OUT_43_WORDLENGTH      8
#define OUT_43_FIXPOINTSCALING 1
#define OUT_43_FRACTIONLENGTH  3
#define OUT_43_BIAS            0
#define OUT_43_SLOPE           0.125
/* Output Port  44 */
#define OUT_PORT_44_NAME      gear_compression
#define OUTPUT_44_WIDTH       3
#define OUTPUT_DIMS_44_COL    1
#define OUTPUT_44_DTYPE       real32_T
#define OUTPUT_44_COMPLEX     COMPLEX_NO
#define OUT_44_FRAME_BASED    FRAME_NO
#define OUT_44_BUS_BASED      0
#define OUT_44_BUS_NAME       
#define OUT_44_DIMS           1-D
#define OUT_44_ISSIGNED        1
#define OUT_44_WORDLENGTH      8
#define OUT_44_FIXPOINTSCALING 1
#define OUT_44_FRACTIONLENGTH  3
#define OUT_44_BIAS            0
#define OUT_44_SLOPE           0.125
/* Output Port  45 */
#define OUT_PORT_45_NAME      cur_time
#define OUTPUT_45_WIDTH       1
#define OUTPUT_DIMS_45_COL    1
#define OUTPUT_45_DTYPE       uint32_T
#define OUTPUT_45_COMPLEX     COMPLEX_NO
#define OUT_45_FRAME_BASED    FRAME_NO
#define OUT_45_BUS_BASED      0
#define OUT_45_BUS_NAME       
#define OUT_45_DIMS           1-D
#define OUT_45_ISSIGNED        1
#define OUT_45_WORDLENGTH      8
#define OUT_45_FIXPOINTSCALING 1
#define OUT_45_FRACTIONLENGTH  3
#define OUT_45_BIAS            0
#define OUT_45_SLOPE           0.125
/* Output Port  46 */
#define OUT_PORT_46_NAME      warp
#define OUTPUT_46_WIDTH       1
#define OUTPUT_DIMS_46_COL    1
#define OUTPUT_46_DTYPE       uint32_T
#define OUTPUT_46_COMPLEX     COMPLEX_NO
#define OUT_46_FRAME_BASED    FRAME_NO
#define OUT_46_BUS_BASED      0
#define OUT_46_BUS_NAME       
#define OUT_46_DIMS           1-D
#define OUT_46_ISSIGNED        1
#define OUT_46_WORDLENGTH      8
#define OUT_46_FIXPOINTSCALING 1
#define OUT_46_FRACTIONLENGTH  3
#define OUT_46_BIAS            0
#define OUT_46_SLOPE           0.125
/* Output Port  47 */
#define OUT_PORT_47_NAME      visibility
#define OUTPUT_47_WIDTH       1
#define OUTPUT_DIMS_47_COL    1
#define OUTPUT_47_DTYPE       real32_T
#define OUTPUT_47_COMPLEX     COMPLEX_NO
#define OUT_47_FRAME_BASED    FRAME_NO
#define OUT_47_BUS_BASED      0
#define OUT_47_BUS_NAME       
#define OUT_47_DIMS           1-D
#define OUT_47_ISSIGNED        1
#define OUT_47_WORDLENGTH      8
#define OUT_47_FIXPOINTSCALING 1
#define OUT_47_FRACTIONLENGTH  3
#define OUT_47_BIAS            0
#define OUT_47_SLOPE           0.125
/* Output Port  48 */
#define OUT_PORT_48_NAME      elevator
#define OUTPUT_48_WIDTH       1
#define OUTPUT_DIMS_48_COL    1
#define OUTPUT_48_DTYPE       real32_T
#define OUTPUT_48_COMPLEX     COMPLEX_NO
#define OUT_48_FRAME_BASED    FRAME_NO
#define OUT_48_BUS_BASED      0
#define OUT_48_BUS_NAME       
#define OUT_48_DIMS           1-D
#define OUT_48_ISSIGNED        1
#define OUT_48_WORDLENGTH      8
#define OUT_48_FIXPOINTSCALING 1
#define OUT_48_FRACTIONLENGTH  3
#define OUT_48_BIAS            0
#define OUT_48_SLOPE           0.125
/* Output Port  49 */
#define OUT_PORT_49_NAME      elevator_trim_tab
#define OUTPUT_49_WIDTH       1
#define OUTPUT_DIMS_49_COL    1
#define OUTPUT_49_DTYPE       real32_T
#define OUTPUT_49_COMPLEX     COMPLEX_NO
#define OUT_49_FRAME_BASED    FRAME_NO
#define OUT_49_BUS_BASED      0
#define OUT_49_BUS_NAME       
#define OUT_49_DIMS           1-D
#define OUT_49_ISSIGNED        1
#define OUT_49_WORDLENGTH      8
#define OUT_49_FIXPOINTSCALING 1
#define OUT_49_FRACTIONLENGTH  3
#define OUT_49_BIAS            0
#define OUT_49_SLOPE           0.125
/* Output Port  50 */
#define OUT_PORT_50_NAME      left_flap
#define OUTPUT_50_WIDTH       1
#define OUTPUT_DIMS_50_COL    1
#define OUTPUT_50_DTYPE       real32_T
#define OUTPUT_50_COMPLEX     COMPLEX_NO
#define OUT_50_FRAME_BASED    FRAME_NO
#define OUT_50_BUS_BASED      0
#define OUT_50_BUS_NAME       
#define OUT_50_DIMS           1-D
#define OUT_50_ISSIGNED        1
#define OUT_50_WORDLENGTH      8
#define OUT_50_FIXPOINTSCALING 1
#define OUT_50_FRACTIONLENGTH  3
#define OUT_50_BIAS            0
#define OUT_50_SLOPE           0.125
/* Output Port  51 */
#define OUT_PORT_51_NAME      right_flap
#define OUTPUT_51_WIDTH       1
#define OUTPUT_DIMS_51_COL    1
#define OUTPUT_51_DTYPE       real32_T
#define OUTPUT_51_COMPLEX     COMPLEX_NO
#define OUT_51_FRAME_BASED    FRAME_NO
#define OUT_51_BUS_BASED      0
#define OUT_51_BUS_NAME       
#define OUT_51_DIMS           1-D
#define OUT_51_ISSIGNED        1
#define OUT_51_WORDLENGTH      8
#define OUT_51_FIXPOINTSCALING 1
#define OUT_51_FRACTIONLENGTH  3
#define OUT_51_BIAS            0
#define OUT_51_SLOPE           0.125
/* Output Port  52 */
#define OUT_PORT_52_NAME      left_aileron
#define OUTPUT_52_WIDTH       1
#define OUTPUT_DIMS_52_COL    1
#define OUTPUT_52_DTYPE       real32_T
#define OUTPUT_52_COMPLEX     COMPLEX_NO
#define OUT_52_FRAME_BASED    FRAME_NO
#define OUT_52_BUS_BASED      0
#define OUT_52_BUS_NAME       
#define OUT_52_DIMS           1-D
#define OUT_52_ISSIGNED        1
#define OUT_52_WORDLENGTH      8
#define OUT_52_FIXPOINTSCALING 1
#define OUT_52_FRACTIONLENGTH  3
#define OUT_52_BIAS            0
#define OUT_52_SLOPE           0.125
/* Output Port  53 */
#define OUT_PORT_53_NAME      right_aileron
#define OUTPUT_53_WIDTH       1
#define OUTPUT_DIMS_53_COL    1
#define OUTPUT_53_DTYPE       real32_T
#define OUTPUT_53_COMPLEX     COMPLEX_NO
#define OUT_53_FRAME_BASED    FRAME_NO
#define OUT_53_BUS_BASED      0
#define OUT_53_BUS_NAME       
#define OUT_53_DIMS           1-D
#define OUT_53_ISSIGNED        1
#define OUT_53_WORDLENGTH      8
#define OUT_53_FIXPOINTSCALING 1
#define OUT_53_FRACTIONLENGTH  3
#define OUT_53_BIAS            0
#define OUT_53_SLOPE           0.125
/* Output Port  54 */
#define OUT_PORT_54_NAME      rudder
#define OUTPUT_54_WIDTH       1
#define OUTPUT_DIMS_54_COL    1
#define OUTPUT_54_DTYPE       real32_T
#define OUTPUT_54_COMPLEX     COMPLEX_NO
#define OUT_54_FRAME_BASED    FRAME_NO
#define OUT_54_BUS_BASED      0
#define OUT_54_BUS_NAME       
#define OUT_54_DIMS           1-D
#define OUT_54_ISSIGNED        1
#define OUT_54_WORDLENGTH      8
#define OUT_54_FIXPOINTSCALING 1
#define OUT_54_FRACTIONLENGTH  3
#define OUT_54_BIAS            0
#define OUT_54_SLOPE           0.125
/* Output Port  55 */
#define OUT_PORT_55_NAME      nose_wheel
#define OUTPUT_55_WIDTH       1
#define OUTPUT_DIMS_55_COL    1
#define OUTPUT_55_DTYPE       real32_T
#define OUTPUT_55_COMPLEX     COMPLEX_NO
#define OUT_55_FRAME_BASED    FRAME_NO
#define OUT_55_BUS_BASED      0
#define OUT_55_BUS_NAME       
#define OUT_55_DIMS           1-D
#define OUT_55_ISSIGNED        1
#define OUT_55_WORDLENGTH      8
#define OUT_55_FIXPOINTSCALING 1
#define OUT_55_FRACTIONLENGTH  3
#define OUT_55_BIAS            0
#define OUT_55_SLOPE           0.125
/* Output Port  56 */
#define OUT_PORT_56_NAME      speedbrake
#define OUTPUT_56_WIDTH       1
#define OUTPUT_DIMS_56_COL    1
#define OUTPUT_56_DTYPE       real32_T
#define OUTPUT_56_COMPLEX     COMPLEX_NO
#define OUT_56_FRAME_BASED    FRAME_NO
#define OUT_56_BUS_BASED      0
#define OUT_56_BUS_NAME       
#define OUT_56_DIMS           1-D
#define OUT_56_ISSIGNED        1
#define OUT_56_WORDLENGTH      8
#define OUT_56_FIXPOINTSCALING 1
#define OUT_56_FRACTIONLENGTH  3
#define OUT_56_BIAS            0
#define OUT_56_SLOPE           0.125
/* Output Port  57 */
#define OUT_PORT_57_NAME      spoilers
#define OUTPUT_57_WIDTH       1
#define OUTPUT_DIMS_57_COL    1
#define OUTPUT_57_DTYPE       real32_T
#define OUTPUT_57_COMPLEX     COMPLEX_NO
#define OUT_57_FRAME_BASED    FRAME_NO
#define OUT_57_BUS_BASED      0
#define OUT_57_BUS_NAME       
#define OUT_57_DIMS           1-D
#define OUT_57_ISSIGNED        1
#define OUT_57_WORDLENGTH      8
#define OUT_57_FIXPOINTSCALING 1
#define OUT_57_FRACTIONLENGTH  3
#define OUT_57_BIAS            0
#define OUT_57_SLOPE           0.125

#define NPARAMS              0

#define SAMPLE_TIME_0        INHERITED_SAMPLE_TIME
#define NUM_DISC_STATES      0
#define DISC_STATES_IC       [0]
#define NUM_CONT_STATES      0
#define CONT_STATES_IC       [0]

#define SFUNWIZ_GENERATE_TLC 1
#define SOURCEFILES "__SFB__"
#define PANELINDEX           6
#define USE_SIMSTRUCT        0
#define SHOW_COMPILE_STEPS   1                   
#define CREATE_DEBUG_MEXFILE 0
#define SAVE_CODE_ONLY       0
#define SFUNWIZ_REVISION     3.0
/* %%%-SFUNWIZ_defines_Changes_END --- EDIT HERE TO _BEGIN */
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
#include "simstruc.h"

extern void BytesToFdm_Outputs_wrapper(const uint8_T *Input,
			uint32_T *Version,
			uint32_T *padding,
			real_T *longitude,
			real_T *latitude,
			real_T *altitude,
			real32_T *agl,
			real32_T *phi,
			real32_T *theta,
			real32_T *psi,
			real32_T *alpha,
			real32_T *beta,
			real32_T *phidot,
			real32_T *thetadot,
			real32_T *psidot,
			real32_T *vcas,
			real32_T *climb_rate,
			real32_T *v_north,
			real32_T *v_east,
			real32_T *v_down,
			real32_T *v_body_u,
			real32_T *v_body_v,
			real32_T *v_body_w,
			real32_T *A_X_pilot,
			real32_T *A_Y_pilot,
			real32_T *A_Z_pilot,
			real32_T *stall_warning,
			real32_T *slip_deg,
			uint32_T *num_engines,
			uint32_T *eng_state,
			real32_T *rpm,
			real32_T *fuel_flow,
			real32_T *fuel_px,
			real32_T *egt,
			real32_T *cht,
			real32_T *mp_osi,
			real32_T *tit,
			real32_T *oil_temp,
			real32_T *oil_px,
			uint32_T *num_tanks,
			real32_T *fuel_quantity,
			uint32_T *num_wheels,
			uint32_T *wow,
			real32_T *gear_pos,
			real32_T *gear_steer,
			real32_T *gear_compression,
			uint32_T *cur_time,
			uint32_T *warp,
			real32_T *visibility,
			real32_T *elevator,
			real32_T *elevator_trim_tab,
			real32_T *left_flap,
			real32_T *right_flap,
			real32_T *left_aileron,
			real32_T *right_aileron,
			real32_T *rudder,
			real32_T *nose_wheel,
			real32_T *speedbrake,
			real32_T *spoilers);

/*====================*
 * S-function methods *
 *====================*/
/* Function: mdlInitializeSizes ===============================================
 * Abstract:
 *   Setup sizes of the various vectors.
 */
static void mdlInitializeSizes(SimStruct *S)
{

    DECL_AND_INIT_DIMSINFO(inputDimsInfo);
    DECL_AND_INIT_DIMSINFO(outputDimsInfo);
    ssSetNumSFcnParams(S, NPARAMS);
     if (ssGetNumSFcnParams(S) != ssGetSFcnParamsCount(S)) {
	 return; /* Parameter mismatch will be reported by Simulink */
     }

    ssSetNumContStates(S, NUM_CONT_STATES);
    ssSetNumDiscStates(S, NUM_DISC_STATES);


    if (!ssSetNumInputPorts(S, NUM_INPUTS)) return;
    /*Input Port 0 */
    ssSetInputPortWidth(S,  0, INPUT_0_WIDTH);
    ssSetInputPortDataType(S, 0, SS_UINT8);
    ssSetInputPortComplexSignal(S, 0, INPUT_0_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 0, INPUT_0_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 0, 1); /*direct input signal access*/


    if (!ssSetNumOutputPorts(S, NUM_OUTPUTS)) return;
    /* Output Port 0 */
    ssSetOutputPortWidth(S, 0, OUTPUT_0_WIDTH);
    ssSetOutputPortDataType(S, 0, SS_UINT32);
    ssSetOutputPortComplexSignal(S, 0, OUTPUT_0_COMPLEX);
    /* Output Port 1 */
    ssSetOutputPortWidth(S, 1, OUTPUT_1_WIDTH);
    ssSetOutputPortDataType(S, 1, SS_UINT32);
    ssSetOutputPortComplexSignal(S, 1, OUTPUT_1_COMPLEX);
    /* Output Port 2 */
    ssSetOutputPortWidth(S, 2, OUTPUT_2_WIDTH);
    ssSetOutputPortDataType(S, 2, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 2, OUTPUT_2_COMPLEX);
    /* Output Port 3 */
    ssSetOutputPortWidth(S, 3, OUTPUT_3_WIDTH);
    ssSetOutputPortDataType(S, 3, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 3, OUTPUT_3_COMPLEX);
    /* Output Port 4 */
    ssSetOutputPortWidth(S, 4, OUTPUT_4_WIDTH);
    ssSetOutputPortDataType(S, 4, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 4, OUTPUT_4_COMPLEX);
    /* Output Port 5 */
    ssSetOutputPortWidth(S, 5, OUTPUT_5_WIDTH);
    ssSetOutputPortDataType(S, 5, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 5, OUTPUT_5_COMPLEX);
    /* Output Port 6 */
    ssSetOutputPortWidth(S, 6, OUTPUT_6_WIDTH);
    ssSetOutputPortDataType(S, 6, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 6, OUTPUT_6_COMPLEX);
    /* Output Port 7 */
    ssSetOutputPortWidth(S, 7, OUTPUT_7_WIDTH);
    ssSetOutputPortDataType(S, 7, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 7, OUTPUT_7_COMPLEX);
    /* Output Port 8 */
    ssSetOutputPortWidth(S, 8, OUTPUT_8_WIDTH);
    ssSetOutputPortDataType(S, 8, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 8, OUTPUT_8_COMPLEX);
    /* Output Port 9 */
    ssSetOutputPortWidth(S, 9, OUTPUT_9_WIDTH);
    ssSetOutputPortDataType(S, 9, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 9, OUTPUT_9_COMPLEX);
    /* Output Port 10 */
    ssSetOutputPortWidth(S, 10, OUTPUT_10_WIDTH);
    ssSetOutputPortDataType(S, 10, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 10, OUTPUT_10_COMPLEX);
    /* Output Port 11 */
    ssSetOutputPortWidth(S, 11, OUTPUT_11_WIDTH);
    ssSetOutputPortDataType(S, 11, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 11, OUTPUT_11_COMPLEX);
    /* Output Port 12 */
    ssSetOutputPortWidth(S, 12, OUTPUT_12_WIDTH);
    ssSetOutputPortDataType(S, 12, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 12, OUTPUT_12_COMPLEX);
    /* Output Port 13 */
    ssSetOutputPortWidth(S, 13, OUTPUT_13_WIDTH);
    ssSetOutputPortDataType(S, 13, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 13, OUTPUT_13_COMPLEX);
    /* Output Port 14 */
    ssSetOutputPortWidth(S, 14, OUTPUT_14_WIDTH);
    ssSetOutputPortDataType(S, 14, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 14, OUTPUT_14_COMPLEX);
    /* Output Port 15 */
    ssSetOutputPortWidth(S, 15, OUTPUT_15_WIDTH);
    ssSetOutputPortDataType(S, 15, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 15, OUTPUT_15_COMPLEX);
    /* Output Port 16 */
    ssSetOutputPortWidth(S, 16, OUTPUT_16_WIDTH);
    ssSetOutputPortDataType(S, 16, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 16, OUTPUT_16_COMPLEX);
    /* Output Port 17 */
    ssSetOutputPortWidth(S, 17, OUTPUT_17_WIDTH);
    ssSetOutputPortDataType(S, 17, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 17, OUTPUT_17_COMPLEX);
    /* Output Port 18 */
    ssSetOutputPortWidth(S, 18, OUTPUT_18_WIDTH);
    ssSetOutputPortDataType(S, 18, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 18, OUTPUT_18_COMPLEX);
    /* Output Port 19 */
    ssSetOutputPortWidth(S, 19, OUTPUT_19_WIDTH);
    ssSetOutputPortDataType(S, 19, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 19, OUTPUT_19_COMPLEX);
    /* Output Port 20 */
    ssSetOutputPortWidth(S, 20, OUTPUT_20_WIDTH);
    ssSetOutputPortDataType(S, 20, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 20, OUTPUT_20_COMPLEX);
    /* Output Port 21 */
    ssSetOutputPortWidth(S, 21, OUTPUT_21_WIDTH);
    ssSetOutputPortDataType(S, 21, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 21, OUTPUT_21_COMPLEX);
    /* Output Port 22 */
    ssSetOutputPortWidth(S, 22, OUTPUT_22_WIDTH);
    ssSetOutputPortDataType(S, 22, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 22, OUTPUT_22_COMPLEX);
    /* Output Port 23 */
    ssSetOutputPortWidth(S, 23, OUTPUT_23_WIDTH);
    ssSetOutputPortDataType(S, 23, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 23, OUTPUT_23_COMPLEX);
    /* Output Port 24 */
    ssSetOutputPortWidth(S, 24, OUTPUT_24_WIDTH);
    ssSetOutputPortDataType(S, 24, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 24, OUTPUT_24_COMPLEX);
    /* Output Port 25 */
    ssSetOutputPortWidth(S, 25, OUTPUT_25_WIDTH);
    ssSetOutputPortDataType(S, 25, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 25, OUTPUT_25_COMPLEX);
    /* Output Port 26 */
    ssSetOutputPortWidth(S, 26, OUTPUT_26_WIDTH);
    ssSetOutputPortDataType(S, 26, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 26, OUTPUT_26_COMPLEX);
    /* Output Port 27 */
    ssSetOutputPortWidth(S, 27, OUTPUT_27_WIDTH);
    ssSetOutputPortDataType(S, 27, SS_UINT32);
    ssSetOutputPortComplexSignal(S, 27, OUTPUT_27_COMPLEX);
    /* Output Port 28 */
    ssSetOutputPortWidth(S, 28, OUTPUT_28_WIDTH);
    ssSetOutputPortDataType(S, 28, SS_UINT32);
    ssSetOutputPortComplexSignal(S, 28, OUTPUT_28_COMPLEX);
    /* Output Port 29 */
    ssSetOutputPortWidth(S, 29, OUTPUT_29_WIDTH);
    ssSetOutputPortDataType(S, 29, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 29, OUTPUT_29_COMPLEX);
    /* Output Port 30 */
    ssSetOutputPortWidth(S, 30, OUTPUT_30_WIDTH);
    ssSetOutputPortDataType(S, 30, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 30, OUTPUT_30_COMPLEX);
    /* Output Port 31 */
    ssSetOutputPortWidth(S, 31, OUTPUT_31_WIDTH);
    ssSetOutputPortDataType(S, 31, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 31, OUTPUT_31_COMPLEX);
    /* Output Port 32 */
    ssSetOutputPortWidth(S, 32, OUTPUT_32_WIDTH);
    ssSetOutputPortDataType(S, 32, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 32, OUTPUT_32_COMPLEX);
    /* Output Port 33 */
    ssSetOutputPortWidth(S, 33, OUTPUT_33_WIDTH);
    ssSetOutputPortDataType(S, 33, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 33, OUTPUT_33_COMPLEX);
    /* Output Port 34 */
    ssSetOutputPortWidth(S, 34, OUTPUT_34_WIDTH);
    ssSetOutputPortDataType(S, 34, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 34, OUTPUT_34_COMPLEX);
    /* Output Port 35 */
    ssSetOutputPortWidth(S, 35, OUTPUT_35_WIDTH);
    ssSetOutputPortDataType(S, 35, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 35, OUTPUT_35_COMPLEX);
    /* Output Port 36 */
    ssSetOutputPortWidth(S, 36, OUTPUT_36_WIDTH);
    ssSetOutputPortDataType(S, 36, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 36, OUTPUT_36_COMPLEX);
    /* Output Port 37 */
    ssSetOutputPortWidth(S, 37, OUTPUT_37_WIDTH);
    ssSetOutputPortDataType(S, 37, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 37, OUTPUT_37_COMPLEX);
    /* Output Port 38 */
    ssSetOutputPortWidth(S, 38, OUTPUT_38_WIDTH);
    ssSetOutputPortDataType(S, 38, SS_UINT32);
    ssSetOutputPortComplexSignal(S, 38, OUTPUT_38_COMPLEX);
    /* Output Port 39 */
    ssSetOutputPortWidth(S, 39, OUTPUT_39_WIDTH);
    ssSetOutputPortDataType(S, 39, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 39, OUTPUT_39_COMPLEX);
    /* Output Port 40 */
    ssSetOutputPortWidth(S, 40, OUTPUT_40_WIDTH);
    ssSetOutputPortDataType(S, 40, SS_UINT32);
    ssSetOutputPortComplexSignal(S, 40, OUTPUT_40_COMPLEX);
    /* Output Port 41 */
    ssSetOutputPortWidth(S, 41, OUTPUT_41_WIDTH);
    ssSetOutputPortDataType(S, 41, SS_UINT32);
    ssSetOutputPortComplexSignal(S, 41, OUTPUT_41_COMPLEX);
    /* Output Port 42 */
    ssSetOutputPortWidth(S, 42, OUTPUT_42_WIDTH);
    ssSetOutputPortDataType(S, 42, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 42, OUTPUT_42_COMPLEX);
    /* Output Port 43 */
    ssSetOutputPortWidth(S, 43, OUTPUT_43_WIDTH);
    ssSetOutputPortDataType(S, 43, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 43, OUTPUT_43_COMPLEX);
    /* Output Port 44 */
    ssSetOutputPortWidth(S, 44, OUTPUT_44_WIDTH);
    ssSetOutputPortDataType(S, 44, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 44, OUTPUT_44_COMPLEX);
    /* Output Port 45 */
    ssSetOutputPortWidth(S, 45, OUTPUT_45_WIDTH);
    ssSetOutputPortDataType(S, 45, SS_UINT32);
    ssSetOutputPortComplexSignal(S, 45, OUTPUT_45_COMPLEX);
    /* Output Port 46 */
    ssSetOutputPortWidth(S, 46, OUTPUT_46_WIDTH);
    ssSetOutputPortDataType(S, 46, SS_UINT32);
    ssSetOutputPortComplexSignal(S, 46, OUTPUT_46_COMPLEX);
    /* Output Port 47 */
    ssSetOutputPortWidth(S, 47, OUTPUT_47_WIDTH);
    ssSetOutputPortDataType(S, 47, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 47, OUTPUT_47_COMPLEX);
    /* Output Port 48 */
    ssSetOutputPortWidth(S, 48, OUTPUT_48_WIDTH);
    ssSetOutputPortDataType(S, 48, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 48, OUTPUT_48_COMPLEX);
    /* Output Port 49 */
    ssSetOutputPortWidth(S, 49, OUTPUT_49_WIDTH);
    ssSetOutputPortDataType(S, 49, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 49, OUTPUT_49_COMPLEX);
    /* Output Port 50 */
    ssSetOutputPortWidth(S, 50, OUTPUT_50_WIDTH);
    ssSetOutputPortDataType(S, 50, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 50, OUTPUT_50_COMPLEX);
    /* Output Port 51 */
    ssSetOutputPortWidth(S, 51, OUTPUT_51_WIDTH);
    ssSetOutputPortDataType(S, 51, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 51, OUTPUT_51_COMPLEX);
    /* Output Port 52 */
    ssSetOutputPortWidth(S, 52, OUTPUT_52_WIDTH);
    ssSetOutputPortDataType(S, 52, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 52, OUTPUT_52_COMPLEX);
    /* Output Port 53 */
    ssSetOutputPortWidth(S, 53, OUTPUT_53_WIDTH);
    ssSetOutputPortDataType(S, 53, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 53, OUTPUT_53_COMPLEX);
    /* Output Port 54 */
    ssSetOutputPortWidth(S, 54, OUTPUT_54_WIDTH);
    ssSetOutputPortDataType(S, 54, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 54, OUTPUT_54_COMPLEX);
    /* Output Port 55 */
    ssSetOutputPortWidth(S, 55, OUTPUT_55_WIDTH);
    ssSetOutputPortDataType(S, 55, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 55, OUTPUT_55_COMPLEX);
    /* Output Port 56 */
    ssSetOutputPortWidth(S, 56, OUTPUT_56_WIDTH);
    ssSetOutputPortDataType(S, 56, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 56, OUTPUT_56_COMPLEX);
    /* Output Port 57 */
    ssSetOutputPortWidth(S, 57, OUTPUT_57_WIDTH);
    ssSetOutputPortDataType(S, 57, SS_SINGLE);
    ssSetOutputPortComplexSignal(S, 57, OUTPUT_57_COMPLEX);

    ssSetNumSampleTimes(S, 1);
    ssSetNumRWork(S, 0);
    ssSetNumIWork(S, 0);
    ssSetNumPWork(S, 0);
    ssSetNumModes(S, 0);
    ssSetNumNonsampledZCs(S, 0);

    ssSetSimulinkVersionGeneratedIn(S, "8.8");

    /* Take care when specifying exception free code - see sfuntmpl_doc.c */
    ssSetOptions(S, (SS_OPTION_EXCEPTION_FREE_CODE |
                     SS_OPTION_USE_TLC_WITH_ACCELERATOR | 
		     SS_OPTION_WORKS_WITH_CODE_REUSE));
}

#if defined(MATLAB_MEX_FILE)
#define MDL_SET_INPUT_PORT_DIMENSION_INFO
static void mdlSetInputPortDimensionInfo(SimStruct        *S, 
                                         int_T            port,
                                         const DimsInfo_T *dimsInfo)
{
    if(!ssSetInputPortDimensionInfo(S, port, dimsInfo)) return;
}
#endif

#define MDL_SET_OUTPUT_PORT_DIMENSION_INFO
#if defined(MDL_SET_OUTPUT_PORT_DIMENSION_INFO)
static void mdlSetOutputPortDimensionInfo(SimStruct        *S, 
                                          int_T            port, 
                                          const DimsInfo_T *dimsInfo)
{
 if (!ssSetOutputPortDimensionInfo(S, port, dimsInfo)) return;
}
#endif
#define MDL_SET_DEFAULT_PORT_DIMENSION_INFO
static void mdlSetDefaultPortDimensionInfo(SimStruct *S)
{
  DECL_AND_INIT_DIMSINFO(portDimsInfo);
  int_T dims[2] = { INPUT_0_WIDTH, 1 };
  bool  frameIn = ssGetInputPortFrameData(S, 0) == FRAME_YES;

  /* Neither the input nor the output ports have been set */

  portDimsInfo.width   = INPUT_0_WIDTH;
  portDimsInfo.numDims = frameIn ? 2 : 1;
  portDimsInfo.dims    = frameIn ? dims : &portDimsInfo.width;
  if (ssGetInputPortNumDimensions(S, 0) == (-1)) {  
   ssSetInputPortDimensionInfo(S, 0, &portDimsInfo);
  }
  portDimsInfo.width   = OUTPUT_0_WIDTH;
  dims[0]              = OUTPUT_0_WIDTH;
  dims[1]              = 1;
  portDimsInfo.dims    = frameIn ? dims : &portDimsInfo.width;
 if (ssGetOutputPortNumDimensions(S, 0) == (-1)) {  
  ssSetOutputPortDimensionInfo(S, 0, &portDimsInfo);
 }
  return;
}
# define MDL_SET_INPUT_PORT_FRAME_DATA
static void mdlSetInputPortFrameData(SimStruct  *S, 
                                     int_T      port,
                                     Frame_T    frameData)
{
    ssSetInputPortFrameData(S, port, frameData);
}
/* Function: mdlInitializeSampleTimes =========================================
 * Abstract:
 *    Specifiy  the sample time.
 */
static void mdlInitializeSampleTimes(SimStruct *S)
{
    ssSetSampleTime(S, 0, SAMPLE_TIME_0);
    ssSetModelReferenceSampleTimeDefaultInheritance(S);
    ssSetOffsetTime(S, 0, 0.0);
}

#define MDL_SET_INPUT_PORT_DATA_TYPE
static void mdlSetInputPortDataType(SimStruct *S, int port, DTypeId dType)
{
    ssSetInputPortDataType( S, 0, dType);
}
#define MDL_SET_OUTPUT_PORT_DATA_TYPE
static void mdlSetOutputPortDataType(SimStruct *S, int port, DTypeId dType)
{
    ssSetOutputPortDataType(S, 0, dType);
}

#define MDL_SET_DEFAULT_PORT_DATA_TYPES
static void mdlSetDefaultPortDataTypes(SimStruct *S)
{
  ssSetInputPortDataType( S, 0, SS_DOUBLE);
 ssSetOutputPortDataType(S, 0, SS_DOUBLE);
}
/* Function: mdlOutputs =======================================================
 *
*/
static void mdlOutputs(SimStruct *S, int_T tid)
{
    const uint8_T   *Input  = (const uint8_T*) ssGetInputPortSignal(S,0);
    uint32_T        *Version  = (uint32_T *)ssGetOutputPortRealSignal(S,0);
    uint32_T        *padding  = (uint32_T *)ssGetOutputPortRealSignal(S,1);
    real_T        *longitude  = (real_T *)ssGetOutputPortRealSignal(S,2);
    real_T        *latitude  = (real_T *)ssGetOutputPortRealSignal(S,3);
    real_T        *altitude  = (real_T *)ssGetOutputPortRealSignal(S,4);
    real32_T        *agl  = (real32_T *)ssGetOutputPortRealSignal(S,5);
    real32_T        *phi  = (real32_T *)ssGetOutputPortRealSignal(S,6);
    real32_T        *theta  = (real32_T *)ssGetOutputPortRealSignal(S,7);
    real32_T        *psi  = (real32_T *)ssGetOutputPortRealSignal(S,8);
    real32_T        *alpha  = (real32_T *)ssGetOutputPortRealSignal(S,9);
    real32_T        *beta  = (real32_T *)ssGetOutputPortRealSignal(S,10);
    real32_T        *phidot  = (real32_T *)ssGetOutputPortRealSignal(S,11);
    real32_T        *thetadot  = (real32_T *)ssGetOutputPortRealSignal(S,12);
    real32_T        *psidot  = (real32_T *)ssGetOutputPortRealSignal(S,13);
    real32_T        *vcas  = (real32_T *)ssGetOutputPortRealSignal(S,14);
    real32_T        *climb_rate  = (real32_T *)ssGetOutputPortRealSignal(S,15);
    real32_T        *v_north  = (real32_T *)ssGetOutputPortRealSignal(S,16);
    real32_T        *v_east  = (real32_T *)ssGetOutputPortRealSignal(S,17);
    real32_T        *v_down  = (real32_T *)ssGetOutputPortRealSignal(S,18);
    real32_T        *v_body_u  = (real32_T *)ssGetOutputPortRealSignal(S,19);
    real32_T        *v_body_v  = (real32_T *)ssGetOutputPortRealSignal(S,20);
    real32_T        *v_body_w  = (real32_T *)ssGetOutputPortRealSignal(S,21);
    real32_T        *A_X_pilot  = (real32_T *)ssGetOutputPortRealSignal(S,22);
    real32_T        *A_Y_pilot  = (real32_T *)ssGetOutputPortRealSignal(S,23);
    real32_T        *A_Z_pilot  = (real32_T *)ssGetOutputPortRealSignal(S,24);
    real32_T        *stall_warning  = (real32_T *)ssGetOutputPortRealSignal(S,25);
    real32_T        *slip_deg  = (real32_T *)ssGetOutputPortRealSignal(S,26);
    uint32_T        *num_engines  = (uint32_T *)ssGetOutputPortRealSignal(S,27);
    uint32_T        *eng_state  = (uint32_T *)ssGetOutputPortRealSignal(S,28);
    real32_T        *rpm  = (real32_T *)ssGetOutputPortRealSignal(S,29);
    real32_T        *fuel_flow  = (real32_T *)ssGetOutputPortRealSignal(S,30);
    real32_T        *fuel_px  = (real32_T *)ssGetOutputPortRealSignal(S,31);
    real32_T        *egt  = (real32_T *)ssGetOutputPortRealSignal(S,32);
    real32_T        *cht  = (real32_T *)ssGetOutputPortRealSignal(S,33);
    real32_T        *mp_osi  = (real32_T *)ssGetOutputPortRealSignal(S,34);
    real32_T        *tit  = (real32_T *)ssGetOutputPortRealSignal(S,35);
    real32_T        *oil_temp  = (real32_T *)ssGetOutputPortRealSignal(S,36);
    real32_T        *oil_px  = (real32_T *)ssGetOutputPortRealSignal(S,37);
    uint32_T        *num_tanks  = (uint32_T *)ssGetOutputPortRealSignal(S,38);
    real32_T        *fuel_quantity  = (real32_T *)ssGetOutputPortRealSignal(S,39);
    uint32_T        *num_wheels  = (uint32_T *)ssGetOutputPortRealSignal(S,40);
    uint32_T        *wow  = (uint32_T *)ssGetOutputPortRealSignal(S,41);
    real32_T        *gear_pos  = (real32_T *)ssGetOutputPortRealSignal(S,42);
    real32_T        *gear_steer  = (real32_T *)ssGetOutputPortRealSignal(S,43);
    real32_T        *gear_compression  = (real32_T *)ssGetOutputPortRealSignal(S,44);
    uint32_T        *cur_time  = (uint32_T *)ssGetOutputPortRealSignal(S,45);
    uint32_T        *warp  = (uint32_T *)ssGetOutputPortRealSignal(S,46);
    real32_T        *visibility  = (real32_T *)ssGetOutputPortRealSignal(S,47);
    real32_T        *elevator  = (real32_T *)ssGetOutputPortRealSignal(S,48);
    real32_T        *elevator_trim_tab  = (real32_T *)ssGetOutputPortRealSignal(S,49);
    real32_T        *left_flap  = (real32_T *)ssGetOutputPortRealSignal(S,50);
    real32_T        *right_flap  = (real32_T *)ssGetOutputPortRealSignal(S,51);
    real32_T        *left_aileron  = (real32_T *)ssGetOutputPortRealSignal(S,52);
    real32_T        *right_aileron  = (real32_T *)ssGetOutputPortRealSignal(S,53);
    real32_T        *rudder  = (real32_T *)ssGetOutputPortRealSignal(S,54);
    real32_T        *nose_wheel  = (real32_T *)ssGetOutputPortRealSignal(S,55);
    real32_T        *speedbrake  = (real32_T *)ssGetOutputPortRealSignal(S,56);
    real32_T        *spoilers  = (real32_T *)ssGetOutputPortRealSignal(S,57);

    BytesToFdm_Outputs_wrapper(Input, Version, padding, longitude, latitude, altitude, agl, phi, theta, psi, alpha, beta, phidot, thetadot, psidot, vcas, climb_rate, v_north, v_east, v_down, v_body_u, v_body_v, v_body_w, A_X_pilot, A_Y_pilot, A_Z_pilot, stall_warning, slip_deg, num_engines, eng_state, rpm, fuel_flow, fuel_px, egt, cht, mp_osi, tit, oil_temp, oil_px, num_tanks, fuel_quantity, num_wheels, wow, gear_pos, gear_steer, gear_compression, cur_time, warp, visibility, elevator, elevator_trim_tab, left_flap, right_flap, left_aileron, right_aileron, rudder, nose_wheel, speedbrake, spoilers);

}



/* Function: mdlTerminate =====================================================
 * Abstract:
 *    In this function, you should perform any actions that are necessary
 *    at the termination of a simulation.  For example, if memory was
 *    allocated in mdlStart, this is the place to free it.
 */
static void mdlTerminate(SimStruct *S)
{

}

#ifdef  MATLAB_MEX_FILE    /* Is this file being compiled as a MEX-file? */
#include "simulink.c"      /* MEX-file interface mechanism */
#else
#include "cg_sfun.h"       /* Code generation registration function */
#endif


